platform:ios,'7.0'

target 'LBElectricityProject' do

pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry', '~> 1.0.1'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'SDCycleScrollView', '~> 1.65'

end
